services:
  - type: web
    name: health-surveillance-api
    env: python
    buildCommand: pip install -r requirements_render.txt
    startCommand: uvicorn backend.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        value: sqlite:///./health_surveillance.db