@echo off
echo Starting Health Surveillance System...
echo.
echo Starting Backend Server...
start "Backend" cmd /k "cd backend && python -m uvicorn main:app --reload --host 0.0.0.0 --port 8000"
timeout /t 3 /nobreak >nul
echo Starting Frontend Dashboard...
start "Frontend" cmd /k "cd dashboard && npm start"
echo.
echo Both services are starting...
echo Backend: http://localhost:8000
echo Frontend: http://localhost:3000